### ISSUE TITLE
Plugin does not work

### ISSUE THREAD

**Issue by ChristophLu** [enova/pgl_ddl_deploy#71]
Hi,

i want to use this plugin but i cannot get that working - even the example in README. For testing, I used the docker images for postgres.

Steps to reproduce:
* Setup the docker containers (gist here: https://gist.github.com/ChristophLu/0394d204ea4f8a1850d8fa053c01f200)
* Connect to both postgres instances (I used pgAdmin)
* Execute on each: `CREATE EXTENSION pglogical; CREATE EXTENSION pgl_ddl_deploy;`
* In our real environment, the database- and table-owner is "postgres". Saying that, the next line on the provider would be `SELECT pgl_ddl_deploy.add_role(oid) FROM pg_roles WHERE rolname in('postgres', 'replication_role');`, followed by `INSERT INTO pgl_ddl_deploy.set_configs (set_name, include_schema_regex, lock_safe_deployment, allow_multi_statements) VALUES ('default', '.*', true, true);`
* On the subscriber, the role "postgres" already exists, so just execute `SELECT pgl_ddl_deploy.add_role(oid) FROM pg_roles WHERE rolname in('postgres', 'replication_role');`.
* Now execute `SELECT pgl_ddl_deploy.deploy(set_name) FROM pgl_ddl_deploy.set_configs;`

The last step returns `false`, the command line shows:

    WARNING:  Failed execution for id 1 set default
    PL/pgSQL function pgl_ddl_deploy.schema_execute(text,text) line 22 at RAISE
    SQL statement "SELECT pgl_ddl_deploy.schema_execute(p_set_name, 'deploy_sql')"
    PL/pgSQL function pgl_ddl_deploy.deploy(text) line 8 at SQL statement

There is no other error message, no pgl_ddl_deploy tables contain a line except for `set_configs`. The view `event_trigger_schema` is empty.
What is wrong with my setup? I just used the steps from the full example.

Best regards,
Christoph

**Comment by jfinzel** [comment]
@ChristophLu thank you for the report, and please forgive the exceedingly long delay in my response.  It would definitely help to have better context around this error message.

It appears to me that pglogical has changed since this was first developed, in which they used to include standard replication sets in their extension, one of them being called `default`.  This is no longer the case.  See here:
```
# table pglogical.replication_set;
(0 rows)
```

So your problem is that your specified `set_name` which is `default` does not actually exist.  I think if you create it, it should work.  Let me know if it works!

**Comment by ChristophLu** [comment]
Thank you for  the late answer.
Unfortunately, I used another solution since I has not that much time to wait in our project.
