### ISSUE TITLE
Adding table fails on missing index ?!

### ISSUE THREAD

**Issue by depesz** [enova/pgl_ddl_deploy#72]
Hi,
we have pgl_ddl_deploy 2.1 on pg12 -> pg14 upgrade setup, with native logical replication.

At one point in time new table had been added, and pgl_ddl_deploy seems to have caught that it has to be created, but it fails?!

Table on source system looks like:

```
=# \d some_schema.wiki_page_lookups
                                                Table "some_schema.wiki_page_lookups"
     Column      │              Type              │ Collation │ Nullable │                         Default
─────────────────┼────────────────────────────────┼───────────┼──────────┼─────────────────────────────────────────────────────────
 id              │ bigint                         │           │ not null │ nextval('some_schema.wiki_page_lookups_id_seq'::regclass)
 slug            │ text                           │           │ not null │
 wiki_page_id    │ bigint                         │           │ not null │
 root_account_id │ bigint                         │           │ not null │
 context_id      │ bigint                         │           │ not null │
 context_type    │ character varying(255)         │           │ not null │
 created_at      │ timestamp(6) without time zone │           │ not null │
 updated_at      │ timestamp(6) without time zone │           │ not null │
Indexes:
    "wiki_page_lookups_pkey" PRIMARY KEY, btree (id), tablespace "data1"
    "index_wiki_page_lookups_replica_identity" UNIQUE, btree (root_account_id, id) REPLICA IDENTITY, tablespace "data1"
    "unique_index_on_context_and_slug" UNIQUE, btree (context_id, context_type, slug), tablespace "data1"
    "index_wiki_page_lookups_on_wiki_page_id" btree (wiki_page_id), tablespace "data1"
Foreign-key constraints:
    "fk_rails_c478396003" FOREIGN KEY (root_account_id) REFERENCES some_schema.accounts(id)
    "fk_rails_fab897d3f1" FOREIGN KEY (wiki_page_id) REFERENCES some_schema.wiki_pages(id)
Referenced by:
    TABLE "some_schema.wiki_pages" CONSTRAINT "fk_rails_35d1fa9801" FOREIGN KEY (current_lookup_id) REFERENCES some_schema.wiki_page_lookups(id)
Publications:
    "focal14"
Triggers:
    guard_excessive_deletes AFTER DELETE ON some_schema.wiki_page_lookups REFERENCING OLD TABLE AS oldtbl FOR EACH STATEMENT EXECUTE FUNCTION some_schema.guard_excessive_updates()
    guard_excessive_updates AFTER UPDATE ON some_schema.wiki_page_lookups REFERENCING OLD TABLE AS oldtbl FOR EACH STATEMENT EXECUTE FUNCTION some_schema.guard_excessive_updates()
Tablespace: "data1"
```

Upon creation on replica, I'm getting this error:

```
2023-06-07 11:16:58.986 UTC,,,2508549,,6480672a.264705,5,,2023-06-07 11:16:58 UTC,9/43633026,43221883,ERROR,42704,"index ""index_wiki_page_lookups_replica_identity"" for table ""wiki_page_lookups"" does not exist",,,,,"SQL statement ""/*hostname:admin,pid
PL/pgSQL function pgl_ddl_deploy.lock_safe_executor(text) line 6 at EXECUTE
SQL statement ""
        --Be sure to use provider's search_path for SQL environment consistency
            SET SEARCH_PATH TO '';

            SELECT pgl_ddl_deploy.lock_safe_executor($PGL_DDL_DEPLOY$/*hostname:admin,pid:4173706,migration:CreateWikiPageLookups,rake_task:db:migrate:tagged*/ ALTER TABLE ""some_schema"".""wiki_page_lookups"" REPLICA IDENTITY USING INDEX ""index_wiki_page_
            ;
        ""
PL/pgSQL function pgl_ddl_deploy.subscriber_command(name,text[],name,name,text,text,integer,integer,boolean,pgl_ddl_deploy.signals,integer,pgl_ddl_deploy.driver,boolean) line 46 at EXECUTE
SQL statement ""
        SELECT pgl_ddl_deploy.subscriber_command
        (
          p_provider_name := NULL,
          p_set_name := ARRAY['focal14'],
          p_nspname := 'some_schema',
          p_relname := 'wiki_page_lookups',
          p_ddl_sql_sent := $pgl_ddl_deploy_sql$/*hostname:admin,pid:4173706,migration:CreateWikiPageLookups,rake_task:db:migrate:tagged*/ ALTER TABLE ""some_schema"".""wiki_page_lookups"" REPLICA IDENTITY USING INDEX ""index_wiki_page_lookups_replica_ident
          p_full_ddl := $pgl_ddl_deploy_sql$
        --Be sure to use provider's search_path for SQL environment consistency
            SET SEARCH_PATH TO '';

            SELECT pgl_ddl_deploy.lock_safe_executor($PGL_DDL_DEPLOY$/*hostname:admin,pid:4173706,migration:CreateWikiPageLookups,rake_task:db:migrate:tagged*/ ALTER TABLE ""some_schema"".""wiki_page_lookups"" REPLICA IDENTITY USING INDEX ""index_wiki_page_
            ;
        $pgl_ddl_deploy_sql$,
          p_pid := 30803,
          p_set_config_id := 1,
          p_queue_subscriber_failures := false,
          p_signal_blocking_subscriber_sessions := NULL,
          p_lock_timeout := 3000,
          p_driver := 'native'
        );
        ""
PL/pgSQL function pgl_ddl_deploy.execute_queued_ddl() line 55 at EXECUTE",,,,"","logical replication worker",,-1824132553363532961
```

I tried adding this table manually, but then I get error about the table being already there.

Is there anything I can do to fix the situation now?

**Comment by depesz** [comment]
I found the part "Resolving Failed DDL on Subscribers" in docs, but they seem to be rather unclear:

1.  "For the example above of both adding a column and adding a foreign key" - where is the example of adding columns and fkey? I don't see any example directly above
2. "Consume the change in affected replication slot using pg_logical_slot_get_changes up to specific LSN of the transaction which included the DDL statement to get replication working again" - how do I know which lsn to advance to ?

**Comment by jfinzel** [comment]
@depesz the error was:
```
index ""index_wiki_page_lookups_replica_identity"" for table ""wiki_page_lookups"" does not exist
```

Did you try creating this unique index, then allowing the DDL to go through?  Index creation is not replicated.

I submit that I have not really done testing around changing replica identity, so I'm sorry you encountered the issue.

1. for the add columns and fkey example, it is here: https://github.com/enova/pgl_ddl_deploy#ddl-involving-multiple-tables
```sql
ALTER TABLE replicated.foo ADD COLUMN foo_id INT REFERENCES unreplicated.foo (id);
```

2. In terms of using `pg_logical_slot_get_changes`... :(.  This worked with `pglogical`, but it does not work so easily with native because it is binary, and hence you can't really see what is in queue as you can with `pglogical`.  I need to update docs here.

Docs updates are certainly needed.  Another feature that I wanted to add was the ability to override `p_queue_subscriber_failures` in all cases in such a situation, in order that it will queue the failures on the subscriber and allow replication to continue.

I am not able to contribute such a feature at present, though it would be very welcome!  I have gotten around this with the HACK of creating a version of the function `pgl_ddl_deploy.subscriber_command` which forces `p_queue_subscriber_failures` to TRUE, which will store the failed/queued DDL in the subscriber_logs table and allow it to fail.  But if instead the function checked a configuration table (or parameter), this could allow us to override it in case of failures like this.

Please let me know if your situation was resolved.  Thanks for your patience with my slow response.

**Comment by depesz** [comment]
Well, we resolved the case by redoing our replication from scratch. This preblem (replication got stuck on some unreplicated ddl change) has been repeating itself with new tables/columns/whatever.

Next time it will happen, will try with just adding index.

**Comment by jfinzel** [comment]
@depesz I think you are correct, although there is a way to get things rolling still.  I have made a suggested PR with a docs update, specifically with this section: https://github.com/enova/pgl_ddl_deploy/blob/4062ef9b4f3569c746ae53ff6f126b82f7234c62/README.md#no-resolution-last-resort

Please let me know if this works for you and makes sense, or if you have any suggestions.  Thank you for the test case!!!

**Comment by depesz** [comment]
That might help. At the moment we changed our procedure not to change replica identity within the same transaction as table/index creation, so we can fix it manually.

Is there a technical reason why indexes can't be replicated?

**Comment by jfinzel** [comment]
@depesz there are two main reasons that replicating index creation is complicated and why we chose not to do it.  The main one is that often they are created `concurrently`, which won't fly since it will be within a transaction on the subscriber.  We could somehow search for that and modify the SQL, but it would be pretty ugly, and potentially create a long transaction.  A second reason is just that: it could take a long while to execute.

The non-technical reason is that we often want different index configurations on the subscriber.  However, that certainly doesn't apply for constraints.
